name: Caller Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/caller-workflows.yml'
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-print-message.yml
    with:
      message: "Hello from the caller workflow!"
