# Name of the workflow
name: Complex Workflow

# Define events that trigger the workflow
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/conditional.yml'  
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/conditional.yml'  

jobs:
  # First job in the workflow
  job1:
    # Specify the OS for the job
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code from the repository
      - name: Checkouts
        uses: actions/checkout@v2

      # Step to run a simple script
      - name: Run a one-line script
        # Command to run
        run: echo Hello, world!

  # Second job in the workflow
  job2:
    # This job depends on the successful completion of job1
    needs: job1
    # Specify the OS for the job
    runs-on: ubuntu-latest

    # Only run this job if the event is a push and job1 succeeded
    if: github.event_name == 'push' && success()

    steps:
      # Step to check out the code from the repository
      - name: Checkout
        # Use the checkout action
        uses: actions/checkout@v2

      # Step to run a different simple script
      - name: Run a different one-line script
        run: echo Hello again, world!
